"""empty message

Revision ID: 06152de35665
Revises: e78bfe8caaa3
Create Date: 2025-05-06 17:48:59.429679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06152de35665'
down_revision = 'e78bfe8caaa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clientes', ['codigoCliente'], ['codigoCliente'])
        batch_op.create_foreign_key(None, 'articulos', ['codigo_articulo'], ['codigo_articulo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
