"""Agregar modelo Pedido

Revision ID: 2ce7601ee3ab
Revises: 1a48097bf593
Create Date: 2025-05-06 16:03:44.995327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce7601ee3ab'
down_revision = '1a48097bf593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedidos_articulos', type_='foreignkey')
        batch_op.drop_constraint('fk_pedidos_clientes', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_pedidos_clientes', 'clientes', ['codigoCliente'], ['codigoCliente'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_pedidos_articulos', 'articulos', ['codigo_articulo'], ['codigo_articulo'], onupdate='CASCADE')

    # ### end Alembic commands ###
