"""Recrear tablas eliminadas

Revision ID: 3da336e28d42
Revises: f2d04d6dd0cd
Create Date: 2025-05-06 14:24:02.401012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3da336e28d42'
down_revision = 'f2d04d6dd0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    op.drop_table('pedidos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id_pedido', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('codigoCliente', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('codigo_articulo', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('fecha_pedido', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['codigoCliente'], ['clientes.codigoCliente'], name='fk_pedidos_clientes', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['codigo_articulo'], ['articulos.codigo_articulo'], name='fk_pedidos_articulos', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id_pedido'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('clientes',
    sa.Column('codigoCliente', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('empresa', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('direccion', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('poblacion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('responsable', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('historial', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('codigoCliente'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
