"""Agregar claves foráneas a la tabla pedidos

Revision ID: e78bfe8caaa3
Revises: 2ce7601ee3ab
Create Date: 2025-05-06 16:14:15.033741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78bfe8caaa3'
down_revision = '2ce7601ee3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index('fk_pedidos_articulos')
        batch_op.drop_index('fk_pedidos_clientes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index('fk_pedidos_clientes', ['codigoCliente'], unique=False)
        batch_op.create_index('fk_pedidos_articulos', ['codigo_articulo'], unique=False)

    # ### end Alembic commands ###
