"""Sincronizar modelos con la base de datos

Revision ID: f2d04d6dd0cd
Revises: 
Create Date: 2025-05-06 14:15:43.143731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2d04d6dd0cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('clientes')
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('importado',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('foto',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('importado',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
        batch_op.alter_column('precio',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=4),
               existing_nullable=False)

    op.create_table('clientes',
    sa.Column('codigoCliente', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('empresa', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('direccion', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('poblacion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('responsable', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('historial', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('codigoCliente'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('codigoCliente', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('codigo_articulo', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('fecha_pedido', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['codigoCliente'], ['clientes.codigoCliente'], name='fk_pedidos_clientes', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['codigo_articulo'], ['articulos.codigo_articulo'], name='fk_pedidos_articulos', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id_pedido'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
